package Encryption;

import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer
{
	public static void main(String[] args) throws Exception 
	{
		int port = 7999;
		ServerSocket server = new ServerSocket(port);
		Socket s = server.accept();

		// YOU NEED TO DO THESE STEPS:
		// -Read the key from the file generated by the client.
		ObjectInputStream in = new ObjectInputStream(new FileInputStream("KeyFile.txt"));
		SecretKey myDesKey = (SecretKey)in.readObject();
		
		// -Use the key to decrypt the incoming message from socket s.
		ObjectInputStream os = new ObjectInputStream(s.getInputStream());
		byte [] encText = (byte [])os.readObject();
		Cipher desCipher;
		desCipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
		desCipher.init(Cipher.DECRYPT_MODE, myDesKey);
		
		byte[] plainText = desCipher.doFinal(encText);
		
		// -Print out the decrypt String to see if it matches the orignal message.
		System.out.println("plain text is: "+ new String(plainText));
		
	}
}
